// <auto-generated />
using System;
using MedicalSupplies.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MedicalSupplies.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615054710_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("MedicalSupplies.Mvc.Models.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Issues", (string)null);
                });

            modelBuilder.Entity("MedicalSupplies.Mvc.Models.IssueItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IssueId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplyId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IssueId");

                    b.HasIndex("SupplyId");

                    b.ToTable("IssueItems", (string)null);
                });

            modelBuilder.Entity("MedicalSupplies.Mvc.Models.Supply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplyCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SupplyCategoryId");

                    b.ToTable("Supplies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Barcode = "893001",
                            Code = "MS001",
                            LastUpdated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Khẩu trang y tế 4 lớp",
                            Price = 50000m,
                            Provider = "MediPlast",
                            Quantity = 1000,
                            SupplyCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Barcode = "893002",
                            Code = "MS002",
                            LastUpdated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Găng tay y tế Nitrile",
                            Price = 80000m,
                            Provider = "VGlove",
                            Quantity = 500,
                            SupplyCategoryId = 1
                        },
                        new
                        {
                            Id = 3,
                            Barcode = "893003",
                            Code = "MS003",
                            LastUpdated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bơm tiêm nhựa 5ml",
                            Price = 1500m,
                            Provider = "Vinahoc",
                            Quantity = 0,
                            SupplyCategoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Barcode = "893004",
                            Code = "MS004",
                            LastUpdated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Dây truyền dịch",
                            Price = 8000m,
                            Provider = "Danapha",
                            Quantity = 15,
                            SupplyCategoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            Barcode = "893005",
                            Code = "MS005",
                            LastUpdated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Máy đo huyết áp điện tử",
                            Price = 1200000m,
                            Provider = "Omron",
                            Quantity = 15,
                            SupplyCategoryId = 3
                        });
                });

            modelBuilder.Entity("MedicalSupplies.Mvc.Models.SupplyCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SupplyCategories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Vật tư tiêu hao"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dụng cụ tiêm truyền"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Thiết bị y tế"
                        });
                });

            modelBuilder.Entity("MedicalSupplies.Mvc.Models.IssueItem", b =>
                {
                    b.HasOne("MedicalSupplies.Mvc.Models.Issue", "Issue")
                        .WithMany("IssueItems")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MedicalSupplies.Mvc.Models.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Issue");

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("MedicalSupplies.Mvc.Models.Supply", b =>
                {
                    b.HasOne("MedicalSupplies.Mvc.Models.SupplyCategory", "Category")
                        .WithMany("Supplies")
                        .HasForeignKey("SupplyCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MedicalSupplies.Mvc.Models.Issue", b =>
                {
                    b.Navigation("IssueItems");
                });

            modelBuilder.Entity("MedicalSupplies.Mvc.Models.SupplyCategory", b =>
                {
                    b.Navigation("Supplies");
                });
#pragma warning restore 612, 618
        }
    }
}
